Явное указание что лицензия - это шаблон
vanessa-opensource/vanessa-bootstrap pull request #7
Opened 2021-02-13 21:43 UTC by aliczin

2021-02-14 00:14 UTC, sfaqer requested changes

2021-02-14 00:14 UTC, sfaqer commented on LICENSE
> +ЭТО ШАБЛОН лиценщионного соглашения. Пожалуйста измените его после создания своего репозитория
Очепятка: "лиценшионного"

2021-02-14 06:56 UTC, aliczin commented on LICENSE
> +ЭТО ШАБЛОН лиценщионного соглашения. Пожалуйста измените его после создания своего репозитория
> Очепятка: "лиценшионного"

Спасибо.

2021-02-14 07:17 UTC, sfaqer approved these changes

2021-02-19 15:24 UTC, merged

2021-02-19 15:25 UTC, artbear commented
@aliczin Большое спасибо!